language: python

python:
  - "3.4"

sudo: false

before_install:
  - pip install -r "web-dashboards/requirements.txt"
  - pip install flake8
  - pip install coveralls

# install:
#   - ./setup.py install

script:
  - flake8 web-dashboards

