language: python

python:
  - "3.4"

sudo: false

services:
  - mongodb
  - elasticsearch

before_install:
  - sleep 15
  - tar xfz web-dashboards/ossmeter-metrics/data/mongo-ossmeter-dump.tgz
  - mongorestore dump
  - pip install -r "web-dashboards/requirements.txt"
  - pip install flake8
  - pip install coveralls
  - pip install pymongo

# install:
#   - ./setup.py install

script:
  - flake8 web-dashboards
  - web-dashboards/ossmeter-metrics/mongo2es.py -g -a -e http://localhost:9200 -i ossmeter

